## name: Black Theme
## author: custom
## blurb: Pure black theme with transparency

background            #000000
foreground            #ffffff
selection_background  #44475a
selection_foreground  #ffffff
cursor                #ffffff
cursor_text_color     #000000

# Black + DarkGrey
color0                #000000
color8                #545454

# DarkRed + Red
color1                #ff5555
color9                #ff6e67

# DarkGreen + Green
color2                #50fa7b
color10               #5af78e

# DarkYellow + Yellow
color3                #f1fa8c
color11               #f4f99d

# DarkBlue + Blue
color4                #bd93f9
color12               #caa9fa

# DarkMagenta + Magenta
color5                #ff79c6
color13               #ff92d0

# DarkCyan + Cyan
color6                #8be9fd
color14               #9aedfe

# LightGrey + White
color7                #bfbfbf
color15               #e6e6e6
