#!/usr/bin/env bash

set -euo pipefail

COLORS_JSON="$HOME/.config/noctalia/colors.json"
GTK3_COLORS="$HOME/.config/gtk-3.0/noctalia-colors.css"
GTK4_COLORS="$HOME/.config/gtk-4.0/noctalia-colors.css"
GTK3_CSS="$HOME/.config/gtk-3.0/gtk.css"
GTK4_CSS="$HOME/.config/gtk-4.0/gtk.css"
KITTY_COLORS="$HOME/.config/kitty/current-theme.conf"
IMPORT_LINE='@import url("noctalia-colors.css");'

if [[ ! -f "$COLORS_JSON" ]]; then
    echo "[theme-sync] ERROR: $COLORS_JSON not found" >&2
    exit 1
fi

c() { jq -r ".$1" "$COLORS_JSON"; }

mSurface=$(c mSurface)
mSurfaceVariant=$(c mSurfaceVariant)
mOnSurface=$(c mOnSurface)
mOnSurfaceVariant=$(c mOnSurfaceVariant)
mPrimary=$(c mPrimary)
mOnPrimary=$(c mOnPrimary)
mSecondary=$(c mSecondary)
mTertiary=$(c mTertiary)
mError=$(c mError)
mOnError=$(c mOnError)
mOutline=$(c mOutline)

echo "[theme-sync] primary=$mPrimary surface=$mSurface"

generate_gtk_colors() {
cat << EOF
/* Generated by theme-sync.sh — do not edit manually */
/* Source: ~/.config/noctalia/colors.json */

@define-color accent_color           $mPrimary;
@define-color accent_bg_color        $mPrimary;
@define-color accent_fg_color        $mOnPrimary;

@define-color destructive_color      $mError;
@define-color destructive_bg_color   $mError;
@define-color destructive_fg_color   $mOnError;

@define-color success_color          $mTertiary;
@define-color warning_color          $mSecondary;
@define-color error_color            $mError;

@define-color window_bg_color        $mSurface;
@define-color window_fg_color        $mOnSurface;

@define-color view_bg_color          $mSurface;
@define-color view_fg_color          $mOnSurface;

@define-color headerbar_bg_color     $mSurfaceVariant;
@define-color headerbar_fg_color     $mOnSurface;
@define-color headerbar_border_color $mOutline;

@define-color card_bg_color          $mSurfaceVariant;
@define-color card_fg_color          $mOnSurface;

@define-color dialog_bg_color        $mSurfaceVariant;
@define-color dialog_fg_color        $mOnSurface;

@define-color popover_bg_color       $mSurfaceVariant;
@define-color popover_fg_color       $mOnSurface;

@define-color sidebar_bg_color                  $mSurface;
@define-color sidebar_fg_color                  $mOnSurface;
@define-color sidebar_backdrop_color            $mSurface;

@define-color secondary_sidebar_bg_color        $mSurfaceVariant;
@define-color secondary_sidebar_fg_color        $mOnSurface;
@define-color secondary_sidebar_backdrop_color  $mSurfaceVariant;

@define-color headerbar_backdrop_color          $mSurface;

@define-color thumbnail_bg_color                $mSurfaceVariant;
@define-color thumbnail_fg_color     $mOnSurface;
EOF
}

generate_gtk_colors > "$GTK3_COLORS"
generate_gtk_colors > "$GTK4_COLORS"
echo "[theme-sync] Generated GTK color variables"

ensure_import() {
    local css_file="$1"
    if [[ ! -f "$css_file" ]]; then
        echo "$IMPORT_LINE" > "$css_file"
    elif ! grep -qF "$IMPORT_LINE" "$css_file"; then
        local tmp; tmp=$(mktemp)
        { echo "$IMPORT_LINE"; echo ""; cat "$css_file"; } > "$tmp"
        mv "$tmp" "$css_file"
    fi
}

ensure_import "$GTK3_CSS"
ensure_import "$GTK4_CSS"
echo "[theme-sync] GTK CSS imports verified"

cat > "$KITTY_COLORS" << EOF
# Generated by theme-sync.sh — do not edit manually
# Source: ~/.config/noctalia/colors.json

background            $mSurface
foreground            $mOnSurface
cursor                $mPrimary
cursor_text_color     $mOnPrimary
selection_background  $mSurfaceVariant
selection_foreground  $mOnSurface

# 16-color palette mapped from Noctalia tokens
color0   $mSurface
color1   $mError
color2   $mPrimary
color3   $mSecondary
color4   $mOnSurfaceVariant
color5   $mPrimary
color6   $mSecondary
color7   $mOnSurface
color8   $mSurfaceVariant
color9   $mError
color10  $mPrimary
color11  $mSecondary
color12  $mOnSurfaceVariant
color13  $mPrimary
color14  $mSecondary
color15  $mOnSurface
EOF
echo "[theme-sync] Generated kitty colors"

if pgrep -x kitty > /dev/null 2>&1; then
    kill -SIGUSR1 $(pgrep -x kitty) 2>/dev/null || true
    echo "[theme-sync] Reloaded kitty"
fi

systemctl --user restart polkit-agent.service 2>/dev/null || true
echo "[theme-sync] Restarted polkit agent"

gsettings set org.gnome.desktop.interface accent-color 'purple' 2>/dev/null || true

notify-send -u low -i preferences-desktop-color "Theme Sync" "System theme synced to $mPrimary"
echo "[theme-sync] Done — synced from Noctalia ($mPrimary)"
