
[GENERAL]
CONFIG_FILE_REVISION=1.3.0

INSTANCE_ID="documents_remote"

INITIATOR_SYNC_DIR="/home/kirill/Documents/remote"
TARGET_SYNC_DIR="ssh://ubuntu@ubuntu:22//home/ubuntu/Documents/remote"

SSH_RSA_PRIVATE_KEY="/home/kirill/.ssh/id_ed25519"

SSH_PASSWORD_FILE=""

_REMOTE_TOKEN=SomeAlphaNumericToken9

CREATE_DIRS=true

LOGFILE="/home/kirill/.cache/osync/documents_remote.log"

MINIMUM_SPACE=10240
BANDWIDTH=0

SUDO_EXEC=false
RSYNC_EXECUTABLE=rsync
RSYNC_REMOTE_PATH=""

RSYNC_PATTERN_FIRST=include
RSYNC_INCLUDE_PATTERN=""
RSYNC_EXCLUDE_PATTERN=".git;.svn;.hg;node_modules;__pycache__;.venv;venv;target;dist;build;.cache;.mypy_cache;.pytest_cache;.smart-env;.DS_Store;*.pyc;*.swp;*.tmp;*.part;.osync-part"
RSYNC_INCLUDE_FROM=""
RSYNC_EXCLUDE_FROM=""
PATH_SEPARATOR_CHAR=";"

INITIATOR_CUSTOM_STATE_DIR=""
TARGET_CUSTOM_STATE_DIR=""

[REMOTE_OPTIONS]

SSH_COMPRESSION=false
SSH_IGNORE_KNOWN_HOSTS=false
SSH_CONTROLMASTER=false
REMOTE_HOST_PING=false
REMOTE_3RD_PARTY_HOSTS=""

[MISC_OPTIONS]

RSYNC_OPTIONAL_ARGS="--partial --partial-dir=.osync-part --timeout=120"

PRESERVE_PERMISSIONS=true
PRESERVE_OWNER=false
PRESERVE_GROUP=false
PRESERVE_EXECUTABILITY=true
PRESERVE_ACL=false
PRESERVE_XATTR=false
COPY_SYMLINKS=false
KEEP_DIRLINKS=false
PRESERVE_HARDLINKS=false
CHECKSUM=false

RSYNC_COMPRESS=true

SOFT_MAX_EXEC_TIME=1800
HARD_MAX_EXEC_TIME=3600
KEEP_LOGGING=1801
MIN_WAIT=60
MAX_WAIT=7200

[BACKUP_DELETE_OPTIONS]

LOG_CONFLICTS=false
ALERT_CONFLICTS=false
CONFLICT_BACKUP=true
CONFLICT_BACKUP_MULTIPLE=false
CONFLICT_BACKUP_DAYS=30
CONFLICT_PREVALANCE=initiator

SOFT_DELETE=true
SOFT_DELETE_DAYS=30

SKIP_DELETION=
SYNC_TYPE=

[RESUME_OPTIONS]

RESUME_SYNC=true
RESUME_TRY=2
FORCE_STRANGER_LOCK_RESUME=false
PARTIAL=false
DELTA_COPIES=true

[ALERT_OPTIONS]
DESTINATION_MAILS=""
ALWAYS_SEND_MAILS=false
MAIL_BODY_CHARSET=""
SENDER_MAIL="alert@your.system.tld"
SMTP_SERVER=smtp.your.isp.tld
SMTP_PORT=25
SMTP_ENCRYPTION=none
SMTP_USER=
SMTP_PASSWORD=

[EXECUTION_HOOKS]

LOCAL_RUN_BEFORE_CMD=""
LOCAL_RUN_AFTER_CMD=""
REMOTE_RUN_BEFORE_CMD=""
REMOTE_RUN_AFTER_CMD=""
MAX_EXEC_TIME_PER_CMD_BEFORE=0
MAX_EXEC_TIME_PER_CMD_AFTER=0
STOP_ON_CMD_ERROR=true
RUN_AFTER_CMD_ON_ERROR=false
