osc = no
border = no
window-maximized=no
geometry=1280x720

sub-fonts-dir=~~/fonts

sub-auto=fuzzy
ytdl-raw-options=sub-lang="en",write-sub=,write-auto-sub=
sub-font='Noto Color Emoji'

[crop-pillar96]
profile-cond=filename and (string.find(filename,"JIG9MQiRTt4",1,true) or string.find(filename,"NQe5_IBt5KE",1,true) or string.find(filename,"m6eKO6-o6BQ",1,true) or string.find(filename,"kmgcnA7ayZo",1,true) or string.find(filename,"hSFTTgGNGRI",1,true) or string.find(filename,"L_VDsP9_ty8",1,true))
profile-restore=copy
video-crop=1728x1080+96+0

[crop-4x3]
profile-cond=filename and (string.find(filename,"mie6z_xLKRI",1,true) or string.find(filename,"lwNnjONc50Y",1,true))
profile-restore=copy
video-crop=1440x1080+240+0

[crop-combinatorics]
profile-cond=filename and string.find(filename,"_cJctOIXWE4",1,true)
profile-restore=copy
video-crop=1460x1036+230+42

[crop-numbertheory]
profile-cond=filename and string.find(filename,"QQEJVbGD8Ho",1,true)
profile-restore=copy
video-crop=1460x1034+230+44

[crop-analysis]
profile-cond=filename and string.find(filename,"am2GiV00Fm0",1,true)
profile-restore=copy
video-crop=1778x1078+72+0

[crop-basics]
profile-cond=filename and string.find(filename,"Ft_3jDl3qxQ",1,true)
profile-restore=copy
video-crop=1190x720+46+0
